x-plane:
  connection:
    serial:
      device: /dev/tty.usbserial-143110
      baud: 9600
      timeout: 5
    network:
      host: localhost
      xpport: 49009
      port: 0
      timeout: 2000
  output:
    filename: output.csv
